import { Inter, Roboto_Serif } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

export const inter = Inter({ subsets: ["latin"] });
export const roboto_serif = Roboto_Serif({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Codeforces Rankrover",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto_serif.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
